apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DATABASE_NAME: cm9hZGNhc3Q= # Base64-encoded value of "roadcast"
  DATABASE_USER: c2lkCg==     # Base64-encoded value of "admin"
  DATABASE_PASSWORD: c2lkCg== # Base64-encoded value of "admin"
