version: '3.8'

services:
  backend:
    build: ./attendance-backend
    container_name: django-backend
    command: gunicorn attendance_management.wsgi --bind 0.0.0.0:8000
    restart: always
    volumes:
      - ./media:/app/media
    env_file:
      - .env
    environment:
      - DEBUG=False
    depends_on:
      - postgres

  frontend:
    build: ./attendance-frontend
    container_name: react-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres_attendance_management
    restart: always
    environment:
      POSTGRES_DB: roadcast
      POSTGRES_USER: sid
      POSTGRES_PASSWORD: sid
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: