version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=roadcast
      - POSTGRES_USER=sid
      - POSTGRES_PASSWORD=sid
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./attendance-backend
    environment:
      - DEBUG=False
    depends_on:
      - postgres

  frontend:
    build: ./attendance-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: