services:
  backend:
    build:
      context: ./attendance-backend
      dockerfile: Dockerfile
    container_name: django-backend
    command: gunicorn attendance_management.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./attendance-backend:/app  # Mount backend code for hot reloading
    env_file:
      - .env
    environment:
      - DEBUG=False
    depends_on:
      - postgres  # Ensure PostgreSQL starts before the backend

  frontend:
    build:
      context: ./attendance-frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    volumes:
    - ./attendance-frontend:/app # Mount frontend code for hot reloading

  postgres:
    image: postgres:latest
    container_name: postgres_attendance_management
    restart: always
    environment:
      POSTGRES_DB: roadcast
      POSTGRES_USER: sid
      POSTGRES_PASSWORD: sid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - :80:8080
  #   volumes:
  #     - ./nginx/niginx-setup.config:/etc/nginx/conf.d/default.conf:ro
  #     - attendance-fronted:/var/www/attendance-frontend
  #   depends_on:
  #     - backend
  #     - fronted

volumes:
  postgres_data:  # Global named volume for PostgreSQL