apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cm9hZGNhc3Q=    # Base64-encoded value of "roadcast"
  POSTGRES_USER: YWRtaW4=      # Base64-encoded value of "admin"
  POSTGRES_PASSWORD: YWRtaW4=  # Base64-encoded value of "admin"
