# Generated by Django 5.1.4 on 2024-12-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyoff',
            name='shift',
        ),
    ]
