# Generated by Django 5.1.4 on 2024-12-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_remove_weeklyoff_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='day_of_week',
        ),
    ]
