# Generated by Django 5.1.4 on 2024-12-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_remove_shift_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershiftmapping',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=10),
        ),
    ]
