# Generated by Django 5.1.4 on 2024-12-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.shift'),
        ),
    ]
